import { Folder, File} from "./structure.js";
let home_folder = "~"

//get a folder from its path
function getFolder(ostr, getf=false){
    let str = ostr;
    // if(str.startsWith("~") || str.startsWith("\\")){
    //     str = home_folder + str;
    // }
    if(str.startsWith(home_folder)){
        // do nothing
    }
    else{
        str = curFolder.path + "/" + str;
    }
    let arr = str.split(/\/|\\/).filter((x) => {return x != ""});
    
    let cur = root;
    for(let i = 1; i < arr.length; i ++){
        if(i == arr.length - 1 && getf){
            for(let file of cur.files){
                if(file.name == arr[i]){
                    return file;
                }
            }
            return undefined;
        }


        if(arr[i] == ".") continue;
        if(arr[i] == ".."){
            if(cur.parent){
                cur = cur.parent;
                continue;
            }
            else{
                return undefined;
            }
        }

        let found = false;
        for(let sub of cur.subfolders){
            if(sub.name == arr[i]){
                found = true;
                cur = sub;
                break;
            }
        }
        if(found) continue;
        return undefined;
    }
    return cur;
}

// get a file from its path
function getFile(ostr){
    return getFolder(ostr, true);
}


const cons = document.getElementById("console")
const fixed = document.getElementById("fixedtext")
const consbox = document.getElementById("consolebox")
const prefix = document.getElementById("prefix")
const header = document.getElementById("header");
const ENTER = 13;
const UP = 38;
const DOWN = 40;
const TAB = 9;

var ready = false;
var skipped = false;
const previousCommands = [""];
var commandIndex = 0;


// read directory structure from JSON generated by src/dir_gen.py
async function loadDirectoryStructure() {
    const response = await fetch("generated/directory_structure.json");
    const structure = await response.json();
    return processDirectory(structure);
}

function processDirectory(directory, parent=undefined) {
    let dir_obj = new Folder(directory.name, parent);
    for (const item of directory.children) {
        if (item.type === "directory") {
            dir_obj.addFolder(processDirectory(item, dir_obj));
        } else if (item.type === "file") {
            let file_obj = new File(item.name, item.contents, true);
            dir_obj.addFile(file_obj);
        } else if(item.type === "served_file") {
            let file_obj = new File(item.name, item.full_path, false);
            dir_obj.addFile(file_obj)
        }
        else{
            throw "Unrecognized file type: " + item.type
        }
        
    }
    return dir_obj;
}

var root = await loadDirectoryStructure();
root.parent = root;
var curFolder = root;


const shortcuts = {
    'piano': "piano/room.html",
    'resume': "Arthur-Bright-Resume.pdf", // TODO: change this
    'github': "https://github.com/arthurbright",
    'linkedin': "https://www.linkedin.com/in/a2bright/",
    'ig': "https://www.instagram.com/artb_64/",
    'youtube': "https://www.youtube.com",
    'spotify': "https://open.spotify.com"
}

// TODO: add a section for math problems!
// TODO: fix bug where links in the projects section show up with <\a> at teh end

function append(str){
    fixed.innerHTML = fixed.innerHTML + str;
    consbox.scrollTop = consbox.scrollHeight;
}

function getPrefix(){
    return '<span class=green>a2bright@my-website</span>:<span class="blue">' + curFolder.path + '</span>$&nbsp;'
}

function setHeader(){
    header.innerHTML = 'a2bright@my-website:&nbsp;' + curFolder.path + ''
}

function animationTimeout(r, duration){
    setTimeout(r, duration);
}


//print big name for startup sequence
async function slowText(str){
    const mod = 4;
    let cnt = 0;
    for(let c of str){
        if(cnt == mod - 1 && !skipped){
            await new Promise(r => animationTimeout(r, 1));
        }
        if(c == "=") append("<br>");
        else append(c);
        cnt = (cnt + 1) % mod;
    }
}


//startup sequence
async function startup(){
    setHeader();
    if(!skipped) await new Promise(r => animationTimeout(r, 100));
    append("<span class='yellow'> Starting up... <\span><br><br>");
    //break up long animation for skipability
    for(let i = 0; i < 16; i ++){
        if(!skipped) await new Promise(r => animationTimeout(r, 50));
    }
    let s = 
    "░█████╗░██████╗░████████╗██╗░░██╗██╗░░░██╗██████╗=" + 
    "██╔══██╗██╔══██╗╚══██╔══╝██║░░██║██║░░░██║██╔══██╗=" + 
    "███████║██████╔╝░░░██║░░░███████║██║░░░██║██████╔╝=" + 
    "██╔══██║██╔══██╗░░░██║░░░██╔══██║██║░░░██║██╔══██╗=" + 
    "██║░░██║██║░░██║░░░██║░░░██║░░██║╚██████╔╝██║░░██║=" + 
    "╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚═╝░░╚═╝=" + 
        "██████╗░██████╗░██╗░██████╗░██╗░░██╗████████╗=" + 
        "██╔══██╗██╔══██╗██║██╔════╝░██║░░██║╚══██╔══╝=" + 
        "██████╦╝██████╔╝██║██║░░██╗░███████║░░░██║░░░=" + 
        "██╔══██╗██╔══██╗██║██║░░╚██╗██╔══██║░░░██║░░░=" + 
        "██████╦╝██║░░██║██║╚██████╔╝██║░░██║░░░██║░░░=" + 
        "╚═════╝░╚═╝░░╚═╝╚═╝░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░=";

    if(window.innerWidth < 550){
        s = 
        "▄▀█ █▀█ ▀█▀ █░█ █░█ █▀█=" + 
        "█▀█ █▀▄ ░█░ █▀█ █▄█ █▀▄==" + 
        "█▄▄ █▀█ █ █▀▀ █░█ ▀█▀=" + 
        "█▄█ █▀▄ █ █▄█ █▀█ ░█░==";
    }

    await slowText(s);

    if(!skipped) await new Promise(r => animationTimeout(r, 100));
    append("<span class='yellow'>Type 'help' to see a list of commands<br><br>");
    for(let i = 0; i < 5; i ++){
        if(!skipped) await new Promise(r => animationTimeout(r, 100));
    }

    ready = true;
    prefix.innerHTML = getPrefix();
}
startup()


//print an error to console
function error(str){
    append("<span class='red'>" + str + "<\span><br>");
}



//process a command (when user presses enter)
function processCommand(str){
    previousCommands.splice(previousCommands.length - 1, 0, str);
    commandIndex = 0;
    let arr = str.split(" ").filter((x) => {return x != ""});
    append(getPrefix() + str + "<br>");
    if(arr.length == 0){
        //do nothing
    }
    else if(arr[0] == "ls"){
        if(arr.length == 1){
            append(curFolder.toString() + "<br>");
        }
        else if(arr.length == 2){
            let folder = getFolder(arr[1]);
            if(folder) append(folder.toString() + "<br>");
            else error(arr[1] + ": Not a directory " + randomEmoji());
        }
        else{
            error('Usage: ls [directory]');
        }
    }
    else if(arr[0] == "cd"){
        if(arr.length == 2){
            let folder = getFolder(arr[1]);
            if(folder) curFolder = folder;
            else error(arr[1] + ": Not a directory " + randomEmoji()); 
            prefix.innerHTML = getPrefix();
            setHeader();
        }
        else{
            error('Usage: cd &lt;directory&gt;');
        }
    }
    else if(arr[0] == "cat"){
        if(arr.length == 2){
            let file = getFile(arr[1]);
            if(file){
                let s = file.getContent();
                if(s) append("<span class='yellow'>" + file.getContent() + "<br> <\span>");
            }
            else error(arr[1] + ": Not a file " + randomEmoji());
        }
        else{
            error('Usage: cat &lt;file-path&gt;');
        }
    }
    else if(arr[0] == "cats"){
        let r = Math.floor(Math.random() * 11);
        window.open("images/cats" + r + ".jpg", '_blank');
    }
    else if(arr[0] == "help"){
        var s = "This website is based on the linux terminal. There are five simple commands:<br>" +
        "&nbsp;&nbsp;cat &lt;file-path&gt;: View the contents of a file.<br>" + 
        "&nbsp;&nbsp;cd &lt;directory&gt;: Change the current directory.<br>" + 
        "&nbsp;&nbsp;help: Display information about commands.<br>" + 
        "&nbsp;&nbsp;ls [directory]: List the contents of a directory, or the current directory if no argument is provided.<br>" + 
        "&nbsp;&nbsp;clear: Clear the terminal.<br><br>" + 
        "You can also use Tab to autofill and the up/down arrow keys to view previous commands. <br>" + 
        "Shortcut commands: resume, github, ig, linkedin, piano. <br>";
        append("<span class='yellow'>" + s + "<br> <\span>");
    }
    else if(arr[0] == "clear"){
        fixed.innerHTML = "";
    }
    else if(arr[0] == "rm"){
        window.open("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    }
    else if(arr[0] in shortcuts){
        window.open(shortcuts[arr[0]], '_blank');
    }
    else{
        error(str + ": Unrecognized command! " + randomEmoji());
    }

}


let cachedOptions = undefined;
let autofillIndex = 0;
let cachedPrefix = undefined;
function autofill(){
    const str = cons.value;
    const words = str.split(' ');

    let numPrevWords = 0;
    for(let i = 0; i < words.length - 1; i ++){
        if(words[i] != '') numPrevWords ++;
    }
    const lastWord = words[words.length - 1];
    
    let options = []
    if(numPrevWords == 0 && lastWord.indexOf('/') == -1 && lastWord.indexOf('\\') == -1){
        //autofill cmds as well
        options = ['cat', 'cd', 'help', 'ls', "clear"];
        for(let k in shortcuts){
            options.push(k)
        }
    }

    let dstr = lastWord;
    if(dstr.startsWith(home_folder)){
        //do nothing
    }
    else{
        dstr = curFolder.path + "/" + dstr;
    }

    let s = Math.max(dstr.lastIndexOf("/"), dstr.lastIndexOf("\\"));
    let pre = dstr.substring(0, s + 1);
    let suf = dstr.substring(s + 1);
    let ogpre = lastWord.substring(0, Math.max(lastWord.lastIndexOf("/"), lastWord.lastIndexOf("\\")) + 1);

    //populate autofill options
    let dir = getFolder(pre, false);
    if(dir == undefined) return;
    for(let sub of dir.subfolders){
        options.push(sub.name + "/");
    }
    for(let file of dir.files){
        options.push(file.name)
    }

    options = [...new Set(options)]; //remove duplicates
    options = options.filter((w) => w.startsWith(suf));
    options.sort();
    if(options.length == 0){
        return; //do nothing
    }

    if(cachedOptions == undefined){
        cachedOptions = options;
        autofillIndex = 0;
        cachedPrefix = ogpre;
    }
    else{
        autofillIndex = (autofillIndex + 1) % cachedOptions.length
    }

    words[words.length - 1] = cachedPrefix + cachedOptions[autofillIndex];
    cons.value = words.join(' ');

    if(cachedOptions.length <= 1){
        clearAutofillCache();
    }
}

function clearAutofillCache(){
    cachedOptions = undefined;
}

//input handlers
cons.onkeydown = e => {
    if (!((e.keyCode && e.keyCode == TAB) || (e.charCode && e.charCode == TAB))){
        clearAutofillCache();
    }

    //skipping the intro animation
    if(!ready && !skipped && e.keyCode && e.keyCode == ENTER){
        e.preventDefault();
        skipped = true;
        cons.innerHTML = ""
        return;
    }

    if(!ready){
        e.preventDefault();
        return;
    }

    if ((e.keyCode && e.keyCode == ENTER) || (e.charCode && e.charCode == ENTER)){
        processCommand(cons.value);
        cons.value = "";
        e.preventDefault();
    }
    else if ((e.keyCode && e.keyCode == UP) || (e.charCode && e.charCode == UP)){
        commandIndex += 1;
        if(commandIndex < 0){
            commandIndex = 0;
            e.preventDefault();
            return;
        }
        if(commandIndex >= previousCommands.length){
            commandIndex = previousCommands.length - 1;
            e.preventDefault();
            return;
        }
        if(commandIndex < previousCommands.length && commandIndex >= 0){
            cons.value = previousCommands[previousCommands.length - 1 - commandIndex];
        }
        e.preventDefault();
    }
    else if ((e.keyCode && e.keyCode == DOWN) || (e.charCode && e.charCode == DOWN)){
        commandIndex -= 1;
        if(commandIndex < 0){
            commandIndex = 0;
            cons.value = "";
            e.preventDefault();
            return;
        }
        if(commandIndex >= previousCommands.length){
            commandIndex = previousCommands.length - 1;
            e.preventDefault();
            return;
        }
        if(commandIndex < previousCommands.length && commandIndex >= 0){
            cons.value = previousCommands[previousCommands.length - 1 - commandIndex];
        }
        e.preventDefault();
    }
    else if ((e.keyCode && e.keyCode == TAB) || (e.charCode && e.charCode == TAB)){
        e.preventDefault();
        autofill();
    }
};


const emojis = [":(", ">:(", ";(", ">;(", "D:", "( ͡° ͜ʖ ͡°)"]
function randomEmoji(){
    return emojis[Math.floor(Math.random() * emojis.length)];
}

